WORKER_LEASE_NAME = "worker"

WORKER_STATUS_STARTING = "starting"
WORKER_STATUS_READY = "ready"
WORKER_STATUS_RUNNING = "running"
WORKER_STATUS_DEGRADED = "degraded"

WORKER_READY_STATUSES = frozenset({WORKER_STATUS_READY, WORKER_STATUS_RUNNING})
